project:
  type: website

website:
  title: "Robot Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: documentation.qmd
        text: Documentation
      - href: fpga.qmd
        text: FPGA
      - href: mcu.qmd
        text: MCU
      - href: team.qmd
        text: The Team
      - href: about.qmd
        text: About
      - href: deliverables.qmd
        text: Early Deliverables

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



